A Series is a one dimensional labele array capable of holding any data type. The axis labels are collectively called the index.

Key Data Structures in Pandas
-> Series
-> DataFrame

In [ ]:
import numpy as np
import pandas as pd

s=pd.Series([1,2,3,4,"ayush"],index=['a','b','c','d','e'])
print(s)

a        1
b        2
c        3
d        4
e    ayush
dtype: object

In [ ]:
import numpy as np
import pandas as pd

y=pd.Series([1,2,3,4,"ayush"])
print(y)

0        1
1        2
2        3
3        4
4    ayush
dtype: object

Data Frames is the twwo dimentional dataStructure.
Syntax for dataFrames:
pd.DataFrame([],column=[],index=[])

Methods to read csv file in pandas

In [ ]:
import pandas as pd
from google.colab import files
uploaded = files.upload()

# Get the name of the uploaded file
file_name = next(iter(uploaded))

df = pd.read_csv(file_name)
df.head(40)
df.tail()
#df.info() #shows memory
df.describe()

Saving sample_student_data.csv to sample_student_data (1).csv

             ID        Age      CGPA
count  5.000000   5.000000  5.000000
mean   3.000000  23.000000  8.360000
std    1.581139   1.581139  0.691375
min    1.000000  21.000000  7.500000
25%    2.000000  22.000000  7.800000
50%    3.000000  23.000000  8.500000
75%    4.000000  24.000000  8.900000
max    5.000000  25.000000  9.100000

There are many different extentions file can we used - parquet, csv, excel file etc.

In [ ]:
#Accessing Data using pandas
# .head() to see the first 5 columns of the file
#  display(file_name)
# .tail() to see the last 5 columns
# .sample(number of column you want to see, random_State=1)
# .loc[#rows,#columns]
#  .loc[0:5,[0,2]] or .loc[:,[0,2,3,4]]
# we can modify the values in a csv file using loc
# .loc[row number,cloumn name]=desired number
df

   ID   Name  Age Department  CGPA
0   1   Amit   22        CSE   8.5
1   2  Priya   24         IT   9.1
2   3  Rahul   21        ECE   7.8
3   4  Sneha   23        CSE   8.9
4   5  Arjun   25         ME   7.5

.loc label (naam) se select karta hai, aur .iloc index number (position) se select karta hai.

In [ ]:
#.sort_values([column_name],ascending=[False])
#.sort_values([a,b],ascending=[0,1])
#

In [ ]:
df['house']="Red"
dg=df.drop(columns=['Age']) #to drop a file
df
dg=df.drop(columns=['Age'],inplace=True) #to drop a file
df

   ID   Name Department  CGPA house
0   1   Amit        CSE   8.5   Red
1   2  Priya         IT   9.1   Red
2   3  Rahul        ECE   7.8   Red
3   4  Sneha        CSE   8.9   Red
4   5  Arjun         ME   7.5   Red

In [ ]:
df[df['Name']=='Amit']['Department'].value_counts()

Department
CSE    1
Name: count, dtype: int64

In [ ]:
df.groupby('Department')['CGPA'].mean()

Department
CSE    8.7
ECE    7.8
IT     9.1
ME     7.5
Name: CGPA, dtype: float64